### ISSUE TITLE
[Question] - Azure deployment

### ISSUE THREAD

**Issue by forero08** [NonFactors/MVC6.Template#31]
Hi!
I added some entities to the orignal model using scaffolding, made some customizations, etc. Now I am trying to deploy the app to an azure AppService and I am getting a `FileNotFoundException` for the `dotnet-gen.dll` file. Migrations were executed because I can see all tables in DB.

Used the `CopyLocalLockFileAssemblies` param with debug condition and without it, published and got the same error.  I'm assuming that removing the reference to `Genny` and the `Templates` folder it could work, but I can't do it yet.

Do you know about any related issue with this or any option to solve it? Any kind of advice is accepted. Check next image please (no public key token and unknown location).

The stacktrace has just one reference to the code in the project: 
`Components\Mvc\Middleware\SecureHeadersMiddleware.cs:line 22` this is: `await Next(context);`

Thanks in advance!

![image](https://user-images.githubusercontent.com/10062459/58372895-790f3e80-7eea-11e9-8284-9af48556b5ab.png)

**Comment by Muchiachio** [comment]
Publishing release build should exclude the template files, if you are using debug build you can try removing `PrivateAssets="All"` from genny and humanizer packages and see if it helps.

**Comment by forero08** [comment]
Thank you so much, it worked and I don't have that error now!!! (I am using release builds).
However, I'm facing a new one and I think its probably related to the Middleware. This is what's happening now: 
- If I deploy using the `ASPNETCORE_ENVIRONMENT` as `Development` the site loads, but the response does not include any javascript or css file. This an example error message that I get using developer tools in firefox: `The resource from “https://XXXXX.azurewebsites.net/Scripts/Shared/public.js” was blocked due to MIME type (“”) mismatch (X-Content-Type-Options: nosniff)`. Its the same for all js and css files.

- If I deploy using the `ASPNETCORE_ENVIRONMENT` as `Production` the site does not load and I get a 500.30 error like this: _HTTP Error 500.30 - ANCM In-Process Start Failure_. Checking the detailed logs I have an  `ObjectDisposedException`. In both lines of the exception the points to the same instruction: `await Next(context);` 

Please let me know if I need to set up any variable or anything else. Any help would be appreciated.

Here is the stacktrace for the second case:
```
Application: w3wp.exe
CoreCLR Version: 4.6.27521.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at XXXXX.Components.Mvc.SecureHeadersMiddleware.Invoke(HttpContext context) in C:\PathToSolution\XXXXX.Components\Mvc\Middleware\SecureHeadersMiddleware.cs:line 22
   at XXXXX.Components.Mvc.ErrorPagesMiddleware.View(HttpContext context, String path) in C:\PathToSolution\XXXXX.Components\Mvc\Middleware\ErrorPagesMiddleware.cs:line 61
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.b__7_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallback.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by Muchiachio** [comment]
Release build generates min.js files, which are then included in the layout with production environment.
You can edit web project file to always include the unminified sources.

As for second error, your azure environment probably doesn't support in process hosting model, you can also remove that from the project configuration in `.Web.csproj`.

**Comment by forero08** [comment]
I had to disable both custom middlewares (`ErrorPagesMiddleware` and `SecureHeadersMiddleware`). Also disabled the `FileLoggerProvider` and it works normally. 
It's a temporal solution to test current development in Azure environment.
